name: ParslPipeline

on:
  push:
    branches: "main"
    tags: ["*"]
  pull_request:
  release:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-parsl:
    timeout-minutes: 60
    name: Test Parsl pipeline
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Remove Julia
        # We want to test the installation of Julia with juliaup within the
        # Parsl pipeline, so we have to remove Julia from this environment.
        run: |
          sudo rm -r /usr/bin/julia /usr/local/julia*
      - name: Make sure Julia is not installed
        # Make sure Julia is indeed not installed at this point, in case the
        # previous step failed to remove all installations of Julia.
        run: |
          if which julia; then
              echo "Julia is installed, make sure it's uninstalled at this point"
              exit 1
          fi
      - uses: julia-actions/cache@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Create virtual environment
        run: |
          python3 -m venv env
          source env/bin/activate
      - name: Install Parsl
        run: |
          pip install .
      - name: Run Parsl pipeline
        run: |
          ./run-lineage-analysis.py
      - name: Add Julia to PATH
        # This is only needed for the post-run hook of the `julia-actions/cache`
        # workflow, which needs `julia` to be available in `PATH`.
        run: |
          echo "PATH=${HOME}/.juliaup/bin:${PATH}" >> "${GITHUB_ENV}"
