name: Tests

on:
  push:
    branches: "main"
    tags: ["*"]
  pull_request:
  release:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-julia:
    timeout-minutes: 60
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version:
          - "1"
        os:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        julia-arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        shell: julia --color=yes --project=. {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Run simple simulation
        shell: julia --color=yes --project=. {0}
        run: |
          include(joinpath(pwd(), "controlgetlineageABCdynamics.jl"))
          controlgetlineageABCdynamics(;
              filename="2024-04-08_13-03-47_Simulation2_cells=3,model=2,pars=[ +4.52000e+02 +5.00000e+00 +3.00000e+03 +2.00000e+00 +5.00000e-01 +2.88000e+02 +0.",
              model=UInt64(11),
              timeresolution=4.0/60,
              nochains=UInt(2),
              MCmax=UInt(30),
              subsample=UInt(2),
              nomothersamples=UInt(300),
              nomotherburnin=UInt(5),
              nolevels=UInt(3),
              notreeparticles=UInt(100)
          )
        env:
          JULIA_NUM_THREADS: 4

  tests-python:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run tests
        run: pytest
